name: Pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/deploy-pages@v4
